### ISSUE TITLE
세가지

### ISSUE THREAD

**Issue by JesungKoo** [Skkrypto/wiki#1]
1. 2/3 합의를 3/5합의로 변경
- 현재 위키 팀원 5명인데 2/3이라는 숫자가 비현실적임.

2. 위키 관리자 추가기준 명시
- 지속적인 관리를 위해 명시해둘 필요가 있음 (hiddenHome 일부 정리기도 함)

3. 소주제이지만 논의할 거리 많은 주제들 추가 디렉토리 생성
- 현재 구현체 디렉토리가 Implementation으로 되어있는데, 하위 디렉토리로 Bitcoin, Ethereum, Hyperledger 만들고 그 안에 관련 md파일 저장하기

**Comment by csy1204** [comment]
1번은 3명 합의 오케이
2번은 케이스 가 여러 개일텐데 예를 들어 새로운 항목을 써야하는데 잘 모를 경우 / 돌연 탈퇴 / 일손 부족 등 기준 몇개 적고 유동적 일단 갈까? 아 그럼 최소인원정도는 무조건 필요할듯

3번 좋음 특히 거대 플랫폼일 수록 꼭 필요함(스팀, 이오스도 나중엔 필요할듯)

**Comment by JesungKoo** [comment]
2번 케이스 여러개인게 확실히 어렵긴 하네.

단순한 방식으론 1번으로 2번도 해결한다 - 즉 추가를 그저 합의만으로 한다가 있겠는데
그럴 경우 돌연 탈퇴의 케이스에서 완전히 파국이 일어날 수도 있는 듯.

그럼 이렇게려나?
1. 최소인원의 기준 - 기준 미달시 무조건적으로 관리자 선발
2. 1번을 전제로 하고 여러가지 분기
 2-1. 기존 관리자들의 능력 부족
 2-2. 절대적인 노동력의 부족(정보가 쏟아지는데 커밋이 계속 지연되면 문제일듯)
 2-3. 그 외 또다른 - ~정 생각 안날 때는 치트조항 "관리자의 재량" 삽입해야지 뭐~ 이건 생각할때마다 이슈로 수정할 수 있는 문제니 너무 깊게 고민할 필요는 없으리라 생각.

**Comment by JesungKoo** [comment]
반영 완료
